# Generated by Django 4.0.4 on 2022-04-22 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commentaire', models.TextField()),
                ('entree', models.CharField(max_length=100)),
                ('principal', models.CharField(max_length=100)),
                ('decert', models.CharField(max_length=100)),
                ('date_commanded', models.DateTimeField(auto_now_add=True)),
                ('date_delivery', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
