# Generated by Django 4.0.4 on 2022-04-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartRest', '0003_rename_entree_commande_cmd_supp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nb_cmd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
